import Head from "next/head";
import React, { useContext } from "react";
import Sidebar from "../../components/Sidebar";
import Chat from "../../components/Chat";
import Auth from "../../utils/Auth";
import MainLayout from "@/layouts/MainLayout";

function Home() {
  return (
    <MainLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="home">
        <div className="container">
          <Sidebar />
          <Chat />
        </div>
      </div>
    </MainLayout>
  );
}

export default Auth(Home);
